# Site
title: Theoria Note
description: 日々の生活に役立たないメモ
url: https://theoria24.github.io
logo: logo.png                                       # Site logo
locale: ja_JP
cardimg: cardimg.png

# Left Block Images
background:
  homepage: images/home.png                           # this image will be shown on homepage's left block
  post-list: images/post.png             # this image will be shown on post list page
  default-post: images/page.png   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /posts/:year/:month/:day/:title.html
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
  coderay_line_numbers: table

sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-77995914-1

# Social Links
email:             theoria23@gmail.com
#google.plus:        117616561992874279869
twitter:            _theoria
#facebook:           username
github:             theoria24
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
steam:              _theoria
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
keybase:           theoria
#xmpp:              username@server.com
#hackernews:        username
#behance:           username
wikipedia:          Theoria24
mastodon:           wug.fun/@theoria

disqus: disqus_GcrjMlrWvK

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-redirect-from

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
